services:
  - type: web
    name: all4youauctioneers-1
    runtime: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: REALTIME_PORT
        value: 10000
    healthCheckPath: /health
    autoDeploy: true