services:
  - type: web
    name: all4you-realtime-service
    runtime: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: REALTIME_PORT
        value: 5001
    healthCheckPath: /health
    autoDeploy: true