services:
  - type: web
    name: all4you-api-gateway
    runtime: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: REALTIME_SERVICE_URL
        value: https://all4you-realtime-service.onrender.com
    healthCheckPath: /health
    autoDeploy: true